=== yingjin/DSpace/dspace/config/citation-config.dtd
<!-- DSpace Custom Submit input form definition language -->
<!-- Ying Jin updated this for adding document type support for DLC, 11/15/2007-->

 <!ELEMENT citation-config (citation-map, citation-definitions, citation-sensitive-fields) >

 <!ELEMENT citation-map (name-map)* >

 <!ELEMENT name-map (map-type)* >
 <!ELEMENT map-type EMPTY >

<!-- How to specify only one of the attributes is required -->
 <!ATTLIST name-map
           scope CDATA #REQUIRED
           citation-name CDATA #IMPLIED>

 <!ATTLIST map-type
           document-type CDATA #IMPLIED
           citation-name NMTOKEN #REQUIRED>

 <!ELEMENT citation-definitions (citation)+ >
 <!ELEMENT citation (field)+ >
 <!ATTLIST citation name NMTOKEN #REQUIRED>
 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, display-format) >
 <!ATTLIST field 
 			required CDATA #IMPLIED
			default-value CDATA #IMPLIED
			max-n-value CDATA #IMPLIED
			max-n-ending CDATA #IMPLIED
			show-if-exist CDATA #IMPLIED
			noshow-if-exist CDATA #IMPLIED
			op CDATA #IMPLIED>

 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 <!ELEMENT display-format (#PCDATA)>
 <!ATTLIST display-format
           multiple-value-seperator CDATA #IMPLIED
           format-it CDATA #IMPLIED>
           
 
 <!ELEMENT citation-sensitive-fields (field-set)* >
 <!ELEMENT field-set (sensitive-field)+ >
 <!ATTLIST field-set name NMTOKEN #REQUIRED>
 
 <!ELEMENT sensitive-field (dc-schema, dc-element, dc-qualifier?) >
  
 <!ATTLIST citation sensitive-fields-name CDATA  #IMPLIED>

=== yingjin/DSpace/dspace/config/citation-config.xml
<?xml version="1.0"?>
<!DOCTYPE citation-config SYSTEM "citation-config.dtd">

<!-- citation-config configs the format of the citation at community level, collection level or a  -->
<!-- document type level. The file is adapted from input-forms.xml.     -->

<!--
    Author: Ying Jin @ 2008
-->

<citation-config>



	<!-- The citation-map maps the community, a collection or a document type to a citation name.    -->
    <!--  (E)* name-map
            (A)** scope: the handle of a community or a collection
            (A)** citation-name: citation name

            (E)** map-type
                (A)*** document-type: the full name of the document type. The name corresponds to the value in dc.type for each item.
                (A)*** citation-name: citation name

    The citation-name is given in name-map will be overwriten by the one given in map-type.

    For example,
        <name-map scope="1911/2946" citation-name="ece-default">
            <map-type document-type="Conference Paper" citation-name="ece-conference" />
        </name-map>

    The citation "ece-default" is applied to the collection with handle "1911/2946". However, the items with document
    type dc.type="Conference Paper" in this collection will be using the citation "ece-conference".

    -->
	<citation-map>

        <!-- SERVER-SPECIFIC -->
        <!-- dspace.rice.edu -->
        <!-- ECE publications -->

        <!--name-map scope="1911/81741" citation-name="ESCI-maps"/-->  <!-- on testing -->

        <name-map scope="1911/10563" citation-name="ece-default">
            <map-type document-type="Conference Paper" citation-name="ece-conference" />
        </name-map>

        <!-- CMC publications -->
        <name-map scope="1911/21945" citation-name="ece-default">
            <map-type document-type="Conference Paper" citation-name="ece-conference" />
        </name-map>

        <!-- DSP publications -->
        <name-map scope="1911/21661" citation-name="ece-default">
            <map-type document-type="Conference Paper" citation-name="ece-conference" />
        </name-map>

        <!-- Americas Original Documents -->
        <name-map scope="1911/9221" citation-name="americas-original"/> 
        <!-- Americas Visual Materials -->
        <name-map scope="1911/21756" citation-name="americas-original"/> 
        <!-- Americas Mora -->
        <name-map scope="1911/21844" citation-name="americas-mora"/> 

        <!-- Americas Translated -->
        <name-map scope="1911/20693" citation-name="americas-translated"/> 

        <name-map scope="1911/13110" citation-name="etd-default"/>

	<!--name-map scope="1911/68494" citation-name="weber-default"/-->

	<name-map scope="1911/64890" citation-name="thresher-default"/>

        <!--name-map scope="1911/77130" citation-name="shepherd-pamphlets"/-->

        <name-map scope="1911/79705" citation-name="patents-default"/>

        <name-map scope="1911/79696" citation-name="haaa-vahf"/>    <!--VAHF -->
        <name-map scope="1911/79695" citation-name="haaa-vahf"/>    <!--HAAA -->
        <name-map scope="1911/36136" citation-name="haaa-vahf"/>    <!--VAHF -->
        <name-map scope="1911/75169" citation-name="haaa-vahf"/>    <!--HAAA -->

	<!-- for historical image default-->
	<!--name-map scope="1911/61408" citation-name="histimage-default"/--> <!-- Events -->
	<!--name-map scope="1911/62306" citation-name="histimage-default"/--> <!-- Key Documents -->
	<!--name-map scope="1911/61406" citation-name="histimage-default"/--> <!-- People -->
	<!--name-map scope="1911/61407" citation-name="histimage-default"/--> <!-- Places -->
	<!--name-map scope="1911/61409" citation-name="histimage-default"/--> <!-- Sports -->
	<!--name-map scope="1911/61410" citation-name="histimage-default"/--> <!-- Various -->

    <!--name-map scope="1911/70649" citation-name="histimage-default"/--> <!-- Correspondence and ephemera from Lovett World Tour -->
    <!--name-map scope="1911/70176" citation-name="histimage-default"/--> <!-- Postcards collected on Lovett World Tour  -->
    <!--name-map scope="1911/69482" citation-name="histimage-default"/--> <!-- World Tour images by Carrington Weems -->

        <!--name-map scope="1911/75565" citation-name="histimage-default"/--> <!-- Oral History -->
        <!--name-map scope="1911/75967" citation-name="histimage-default"/--> <!-- Rice University Sports Videos -->
        <!--name-map scope="1911/35948" citation-name="histimage-default"/--> <!-- History of Rice University -->
        <!--name-map scope="1911/35950" citation-name="histimage-default"/--> <!-- Rice University General announcements  -->
        <!--name-map scope="1911/35952" citation-name="histimage-default"/--> <!-- Rice University Presidential Inauguration Speeches -->

        <name-map scope="1911/77660" citation-name="dataset-default"/>

        <name-map scope="1911/88869" citation-name="baker-default"/>
        <name-map scope="1911/88867" citation-name="baker-default"/>
        <name-map scope="1911/88864" citation-name="baker-default"/>
        <name-map scope="1911/88878" citation-name="baker-default"/>
        <name-map scope="1911/88876" citation-name="baker-default"/>
        <name-map scope="1911/88865" citation-name="baker-default"/>
        <name-map scope="1911/88866" citation-name="baker-default"/>
        <name-map scope="1911/88870" citation-name="baker-default"/>
        <name-map scope="1911/88881" citation-name="baker-default"/>
        <name-map scope="1911/88874" citation-name="baker-default"/>
        <name-map scope="1911/88868" citation-name="baker-default"/>
        <name-map scope="1911/88875" citation-name="baker-default"/>
        <name-map scope="1911/88873" citation-name="baker-default"/>
        <name-map scope="1911/20460" citation-name="baker-default"/>
        <name-map scope="1911/88879" citation-name="baker-default"/>
        <name-map scope="1911/88872" citation-name="baker-default"/>
        <name-map scope="1911/88871" citation-name="baker-default"/>
        <name-map scope="1911/88880" citation-name="baker-default"/>


        <name-map scope="1911/90431" citation-name="undergraduate-default"/>
        <!-- dspaceland, dspacentest -->
<!--        <name-map scope="1911/2946" citation-name="ece-default">
            <map-type document-type="Conference Paper" citation-name="ece-conference" />
        </name-map>

        <name-map scope="1911/6241" citation-name="americas-original"/>
        <name-map scope="1911/6401" citation-name="americas-original"/>
        <name-map scope="1911/6243" citation-name="americas-original"/>
        <name-map scope="1911/6794" citation-name="americas-mora"/>
        <name-map scope="1911/7843" citation-name="americas-translated"/>
        

        <name-map scope="1911/8598" citation-name="thresher-default"/>

-->
	</citation-map>

	<citation-definitions>

  <!--
    (E)* citation
        (A)** name: citation name, must be unique for all citations defined
        (A)** sensitive-fields-name: The citaton won't be generated if given sensitive field(s) are null or empty.
        (E)** field
            (E)*** max-n-value: designed with max-n-ending attribute for author display.
                Use Case -  if an item has more than 3 authors, and the citation will only display first 3 authors
                            and replace other authors with "et al.", you can put max-n-value="3" max-n-ending="et al."
                            attributes in the author field
            (E)*** max-n-ending: see max-n-value
            (E)*** noshow-if-exist: don't show this field if specified field(s) exists.
                Sample Value: "dc.contributor.author" or "dc.pubplace;dc.contributor.publisher" (multiple fields seperated with ";")
            (E)*** show-if-exist: show this field if specified field(s) exists.
                Sample Value: "dc.contributor.author" or "dc.pubplace;dc.contributor.publisher" (multiple fields seperated with ";")
            (E)*** op: used with noshow-if-exist or show-if-exist when there are multiple fields specified. Value set is ("AND", "OR")
            (A)*** dc-schema: you can specify any schema here, dc or whatever you name it
            (A)*** dc-element: the element name
            (A)*** dc-qualifier: the qualifier name
            (A)*** display-format: Here is the place you can format your citation.
                    @field@ will be replaced by the actural field value. Also you can apply html tags. See [Note 1]
                    for supported html tags.
                (E)**** multiple-value-seperator: Use this seperator to seperate multiple-value field. Default is ", ".
                (E)**** format-it: The attribute is used to customize the field value - @field@ itself.
                        In dspace-api/.../app/util/FormatIt.java, you will find a method formatIt. All format-it attributes are
                        handled over here. Here are the steps to format your field (for multiple-value field, it formats
                        each individual value.)
                        Step 1 - Name your format, for example "firstname-initial-only"
                        Step 2 - Write your format method in FormatIt.java, for example,
                            String getFirstNameInitials(String value)
                        Step 3 - add a line to formatIt method
                            if(formatit.equalsIgnoreCase("firstname-initial-only")){
                                    return getFirstNameInitials(value);
                            }
                        Of course, you need to compile the code, deploy, and restart the web application.

    Special use case - a field without a field value
            If you would like to put a punctuation or a phrase which is not related to any metadata field in the citation,
            you can leave the dc-schema, dc-element, and dc-qualifier empty, and put whatever you want in display-format.
            For example,
